"""Thesis figures, batch 2 (audit + error-anatomy era). Same house style as figures.py;
regenerated by the same one-command entry point (figures.py imports and calls these).

Run directly: KG_CORE_PATH=data/kg_600k_dedup_core .venv/Scripts/python -m dynamics.figures2
"""
from pathlib import Path
import sys
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

OUT = Path("figures")
OUT.mkdir(exist_ok=True)
THEMES = Path("data/dynamics/themes")

plt.rcParams.update({
    "font.family": "serif", "font.size": 9, "axes.titlesize": 10,
    "axes.labelsize": 9, "legend.fontsize": 8, "xtick.labelsize": 8,
    "ytick.labelsize": 8, "pdf.fonttype": 42,
})


def audit_frontier():
    """Configuration frontier from the precision audit: stream precision with Wilson CIs."""
    arms = [("Lenient", 107, 282, "8/10, $-$1wk"), ("Strict", 102, 238, "8/10"),
            ("Neg.-binomial", 36, 97, "7/10"), ("Template-filtered", 109, 244, "8/10, $-$1wk")]
    fig, ax = plt.subplots(figsize=(6.3, 2.8))
    for i, (name, k, n, gold) in enumerate(arms):
        p, z = k / n, 1.96
        den = 1 + z * z / n
        c = (p + z * z / (2 * n)) / den
        h = z * np.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / den
        col = "#1a5276" if name == "Template-filtered" else "#7f8c8d"
        ax.errorbar(i, 100 * p, yerr=[[100 * (p - (c - h))], [100 * ((c + h) - p)]],
                    fmt="o", ms=6, color=col, capsize=4, lw=1.4, zorder=3)
        ax.annotate(f"{100 * p:.1f}%", (i, 100 * p), xytext=(8, 4),
                    textcoords="offset points", fontsize=8, color=col)
        ax.annotate("gold " + gold + "\n$n=" + str(n) + "$", (i, 20), xytext=(0, -32),
                    textcoords="offset points", ha="center", fontsize=7,
                    color="#555555", annotation_clip=False)
    ax.set_xticks(range(4))
    ax.set_xticklabels([a[0] for a in arms])
    ax.set_ylabel("lifelines judged REAL (%)")
    ax.set_ylim(20, 60)
    ax.set_xlim(-0.5, 3.5)
    ax.spines[["top", "right"]].set_visible(False)
    ax.set_title("Lifeline-level precision by configuration (Wilson 95% CIs)")
    fig.tight_layout()
    fig.subplots_adjust(bottom=0.30)
    fig.savefig(OUT / "audit_frontier.pdf")
    fig.savefig(OUT / "audit_frontier.png", dpi=200)
    print("wrote figures/audit_frontier.pdf (+.png)")


def covid_subgraph():
    """FinDKG-style snapshot: theme 121's co-occurrence subgraph at birth vs three weeks after
    the crash, drawn among the lifeline's members over each week's trailing 8-week window."""
    import networkx as nx
    from dynamics.loader import load_core
    kg = load_core(drop_noise=True)
    mem = pd.read_csv(THEMES / "theme_members_lenient.csv")
    ids = set(mem[mem.theme == 121].ent)
    names = {e: str(kg.id2name[e]) for e in ids}
    panels = [(162, "Birth week 2020-02-03"), (168, "2020-03-16 (crash $+$ 3wk)")]
    graphs = []
    for t, _ in panels:
        G = nx.Graph()
        e = kg.edges[(kg.edges.time > t - 8) & (kg.edges.time <= t)]
        e = e[e.subj.isin(ids) & e.obj.isin(ids) & (e.subj != e.obj)]
        for _, r in e.iterrows():
            w = G.get_edge_data(r.subj, r.obj, {"weight": 0})["weight"] + r.weight
            G.add_edge(int(r.subj), int(r.obj), weight=w)
        graphs.append(G)
    union = nx.Graph()
    for G in graphs:
        union.add_edges_from(G.edges)
    pos = nx.spring_layout(union, seed=42, k=1.05)
    fig, axes = plt.subplots(1, 2, figsize=(6.3, 3.4))
    for ax, G, (t, title) in zip(axes, graphs, panels):
        wts = [0.4 + 0.25 * G[u][v]["weight"] for u, v in G.edges]
        nx.draw_networkx_edges(G, pos, ax=ax, width=wts, edge_color="#95a5a6", alpha=0.8)
        cols = ["#c0392b" if names[n] == "Coronavirus" else "#1a5276" for n in G.nodes]
        nx.draw_networkx_nodes(G, pos, ax=ax, node_size=110, node_color=cols, alpha=0.92)
        nx.draw_networkx_labels(G, pos, ax=ax, font_size=5.6,
                                labels={n: names[n][:16] for n in G.nodes})
        ax.set_title(title + "\n(" + str(G.number_of_nodes()) + " members, "
                     + str(G.number_of_edges()) + " co-occurrence edges)", fontsize=8)
        ax.axis("off")
        ax.margins(0.15)
    fig.suptitle("The COVID lifeline's trailing co-occurrence subgraph", fontsize=10)
    fig.tight_layout()
    fig.savefig(OUT / "covid_subgraph.pdf")
    fig.savefig(OUT / "covid_subgraph.png", dpi=200)
    print("wrote figures/covid_subgraph.pdf (+.png)")


def surprise_series():
    """The detector's surprise statistic in action on the Coronavirus entity."""
    from dynamics.loader import load_core
    from dynamics.velocity import formation_events, entity_week_matrix
    kg = load_core(drop_noise=True)
    ent = next(i for i, n in kg.id2name.items() if str(n) == "Coronavirus")
    M = entity_week_matrix(formation_events(kg), kg.n_entities, kg.n_times)[ent]
    cs = np.concatenate([[0], np.cumsum(M)])
    O = np.zeros(kg.n_times)
    E = np.zeros(kg.n_times)
    z = np.zeros(kg.n_times)
    for w in range(kg.n_times):
        lo_r = max(0, w + 1 - 4)
        lo_b = max(0, lo_r - 26)
        O[w] = cs[w + 1] - cs[lo_r]
        E[w] = (cs[lo_r] - cs[lo_b]) * (4 / 26)
        z[w] = (O[w] - E[w]) / np.sqrt(E[w] + 1)
    dates = pd.to_datetime([kg.date(w) for w in range(kg.n_times)])
    lo, hi = pd.Timestamp("2019-10-01"), pd.Timestamp("2020-06-30")
    m = (dates >= lo) & (dates <= hi)
    fire = next(w for w in range(kg.n_times) if z[w] >= 3 and O[w] >= 6)
    fig, ax = plt.subplots(figsize=(6.3, 2.7))
    ax.bar(dates[m], O[m], width=6, color="#1a5276", alpha=0.85,
           label="observed formations $O_t$ (trailing 4wk)")
    ax.plot(dates[m], E[m], color="#7f8c8d", lw=1.4,
            label="expected $E_t$ (trailing 26wk baseline)")
    ax.axvline(dates[fire], color="#1e8449", lw=1.2,
               label="detector fires ($z \\geq 3$, $O \\geq 6$): " + str(dates[fire].date()))
    ax.axvline(pd.Timestamp("2020-02-24"), color="#c0392b", lw=1.2, ls="--",
               label="market break 2020-02-24")
    ax.set_ylabel("new relationships / 4 weeks")
    ax.legend(frameon=False, fontsize=7, loc="upper left")
    ax.spines[["top", "right"]].set_visible(False)
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
    ax.set_title("Poisson surprise on the Coronavirus entity")
    fig.tight_layout()
    fig.savefig(OUT / "surprise_series.pdf")
    fig.savefig(OUT / "surprise_series.png", dpi=200)
    print("wrote figures/surprise_series.pdf (+.png)  fire week=" + str(dates[fire].date()))


def rank_ecdf():
    """ECDF of RE-GCN test ranks, recurring vs novel (log-x): the bimodal anatomy."""
    zf = np.load("data/dynamics/linkpred/regcn_ranks_abl_base_s0.npz")
    ranks = np.concatenate([zf["ro"], zf["rs"]])
    nov = np.concatenate([zf["novel"], zf["novel"]])
    fig, ax = plt.subplots(figsize=(6.3, 2.7))
    for msk, name, col in ((~nov, "recurring", "#1a5276"), (nov, "novel", "#c0392b")):
        r = np.sort(ranks[msk])
        ax.step(r, np.arange(1, len(r) + 1) / len(r), where="post", color=col, lw=1.5,
                label=name + " (median " + format(round(float(np.median(r))), ",") + ")")
    ax.axvline(10, color="#7f8c8d", lw=0.8, ls=":", label="rank 10")
    ax.set_xscale("log")
    ax.set_xlim(1, 21216)
    ax.set_xlabel("rank of the true entity (of 21,216 candidates, log scale)")
    ax.set_ylabel("cumulative share of queries")
    ax.legend(frameon=False, fontsize=8, loc="upper left")
    ax.spines[["top", "right"]].set_visible(False)
    ax.set_title("Where the truth ranks: recurring vs novel test edges (RE-GCN)")
    fig.tight_layout()
    fig.savefig(OUT / "rank_ecdf.pdf")
    fig.savefig(OUT / "rank_ecdf.png", dpi=200)
    print("wrote figures/rank_ecdf.pdf (+.png)")


def detector_overlay():
    """Global formation series with all three burst detectors (rewritten after the original
    uncommitted version was lost to a git checkout; reproduces figures/detectors.pdf)."""
    from dynamics.loader import load_core
    from dynamics.velocity import formation_events, entity_week_matrix
    from dynamics.burst import kleinberg_bursts, cusum_bursts, bocd_bursts
    kg = load_core(drop_noise=True)
    # each formation event increments both endpoint entities, so halve the entity-sum
    counts = entity_week_matrix(formation_events(kg), kg.n_entities, kg.n_times).sum(axis=0) / 2
    dates = pd.to_datetime([kg.date(w) for w in range(kg.n_times)])
    fig, ax = plt.subplots(figsize=(6.3, 2.8))
    ax.plot(dates, counts, color="#2c3e50", lw=1, zorder=2)
    for s, e, _ in kleinberg_bursts(counts):
        ax.axvspan(dates[s], dates[min(e, len(dates) - 1)], color="#c0392b", alpha=0.25, lw=0)
    for s, e, _ in cusum_bursts(counts):
        ax.axvspan(dates[s], dates[min(e, len(dates) - 1)], facecolor="none",
                   edgecolor="#1e8449", hatch="///", lw=0.4, alpha=0.6)
    ybot = -0.04 * counts.max()
    for s, e, _ in bocd_bursts(counts):
        ax.plot(dates[s], ybot, marker="^", ms=6, color="#6c3483", ls="",
                zorder=3, clip_on=False)
    from matplotlib.patches import Patch
    from matplotlib.lines import Line2D
    ax.legend(handles=[
        Line2D([], [], color="#2c3e50", lw=1, label="formations / week"),
        Patch(facecolor="#c0392b", alpha=0.25, label="Kleinberg burst"),
        Patch(facecolor="none", edgecolor="#1e8449", hatch="///", label="CUSUM regime"),
        Line2D([], [], color="#6c3483", marker="^", ls="", label="BOCD onset (back-dated)"),
    ], loc="upper left", frameon=False, fontsize=7)
    ax.set_ylabel("new relationships / week")
    ax.spines[["top", "right"]].set_visible(False)
    ax.set_title("Global edge-formation series with three burst detectors")
    fig.tight_layout()
    fig.savefig(OUT / "detectors.pdf")
    fig.savefig(OUT / "detectors.png", dpi=200)
    print("wrote figures/detectors.pdf (+.png)")


def main():
    audit_frontier()
    covid_subgraph()
    surprise_series()
    rank_ecdf()
    detector_overlay()


if __name__ == "__main__":
    main()
